// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrt8EUiycAJ8fBu8oKG8yTpAlCxoITSQ',
    appId: '1:423525424223:web:22c6d04543522556834fea',
    messagingSenderId: '423525424223',
    projectId: 'product-db-2ac3b',
    authDomain: 'product-db-2ac3b.firebaseapp.com',
    databaseURL: 'https://product-db-2ac3b-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-2ac3b.appspot.com',
    measurementId: 'G-0716YG3BYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmqG1uh6WSo2-4bTIs5STBAjCgvufALE',
    appId: '1:423525424223:android:4fcade57f0490655834fea',
    messagingSenderId: '423525424223',
    projectId: 'product-db-2ac3b',
    databaseURL: 'https://product-db-2ac3b-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-2ac3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAByv5y2eBUL9XpVQLf3E8QYf3XJvV_2PA',
    appId: '1:423525424223:ios:ee595c1fd2e70f15834fea',
    messagingSenderId: '423525424223',
    projectId: 'product-db-2ac3b',
    databaseURL: 'https://product-db-2ac3b-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-2ac3b.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAByv5y2eBUL9XpVQLf3E8QYf3XJvV_2PA',
    appId: '1:423525424223:ios:671a7e4675954af9834fea',
    messagingSenderId: '423525424223',
    projectId: 'product-db-2ac3b',
    databaseURL: 'https://product-db-2ac3b-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-2ac3b.appspot.com',
    iosBundleId: 'com.example.product.RunnerTests',
  );
}
